using NDatabase2.Btree;
using NDatabase2.Btree.Impl.Multiplevalue;

namespace NDatabase2.Odb.Core.BTree
{
    /// <summary>
    ///   The NDatabase ODB BTree.
    /// </summary>
    /// <remarks>
    ///   The NDatabase ODB BTree. It extends the DefaultBTree implementation to add the ODB OID generated by the ODB database.
    /// </remarks>
    /// <author>osmadja</author>
    public sealed class OdbBtreeMultiple : BTreeMultipleValuesPerKey
    {
        private OID _oid;

        public OdbBtreeMultiple()
        {
        }

        public OdbBtreeMultiple(string name, int degree, IBTreePersister persister) : base(name, degree, persister)
        {
        }

        public override IBTreeNode BuildNode()
        {
            return new OdbBtreeNodeMultiple(this);
        }

        public override object GetId()
        {
            return _oid;
        }

        public override void SetId(object id)
        {
            _oid = (OID) id;
        }
    }
}
