using System;
using NDatabase.Btree;
using NDatabase.Btree.Impl.Multiplevalue;

namespace NDatabase.Odb.Impl.Core.Btree
{
    /// <summary>
    ///   The NDatabase ODB BTree.
    /// </summary>
    /// <remarks>
    ///   The NDatabase ODB BTree. It extends the DefaultBTree implementation to add the ODB OID generated by the ODB database.
    /// </remarks>
    /// <author>osmadja</author>
    [Serializable]
    public class OdbBtreeMultiple : BTreeMultipleValuesPerKey
    {
        private OID _oid;

        public OdbBtreeMultiple()
        {
        }

        public OdbBtreeMultiple(string name, int degree, IBTreePersister persister) : base(name, degree, persister)
        {
        }

        public override IBTreeNode BuildNode()
        {
            return new OdbBtreeNodeMultiple(this);
        }

        public override object GetId()
        {
            return _oid;
        }

        public override void SetId(object id)
        {
            _oid = (OID) id;
        }
    }
}
